### ISSUE TITLE
DatabaseError: Allocation failed for 'SPK5504.SPARK.ZSPARK.CRDEMO.VSAM', missing DD card

### ISSUE THREAD

**Issue by h3xh4wk** [ibmz-community-cloud/zAnalytics#2]
Hi I am facing error while executing the below code as per step mentioned in README (https://github.com/ibmz-community-cloud/zAnalytics#step-5-use-case-2-run-a-python-program-with-jupyter-notebook)

```
client_df = load_data_from_mds(vtable_name='VSAM_CLIENT', user=USERNAME, password=PASSWORD)
client_df = client_df.set_index("cont_id")
client_df
```
Error
```
DatabaseError                             Traceback (most recent call last)
<ipython-input-7-7984040416f2> in <module>()
----> 1 client_df = load_data_from_mds(vtable_name='VSAM_CLIENT', user=USERNAME, password=PASSWORD)
      2 client_df = client_df.set_index("cont_id")
      3 client_df

<ipython-input-2-c90429d7652b> in load_data_from_mds(vtable_name, user, password, mds_id)
     16     conn =dsdbc.connect(SSID=mds_id, user=user, password=password)
     17     cursor = conn.cursor()
---> 18     cursor.execute("SELECT * FROM " + vtable_name)
     19     rows = cursor.fetchall()
     20     label = []

DatabaseError: Allocation failed for 'SPK5504.SPARK.ZSPARK.CRDEMO.VSAM', missing DD card
```

My user is SPK0568 and not SPK5504
Why the Error says `missing DD card` ?
Please can you look into it and let me know if this needs to fixed at your end or I am missing some step. Though optional, I even uploaded vsam data and copybook.

**Comment by zhouxj-ibm** [comment]
Hi:

This is an issue of system cleanup.  The z/OS system was used by another trial user who load VSAM file with the same virtual table name.  Thus he altered the virtual table to map to the VSAM file he uploaded(in this case SPK5504.SPARK.ZSPARK.CRDEMO.VSAM).  When this user is expired, we supposed to clean up the z/OS system, but somehow we failed to re-defined this virtual table.  That cause the problem you encountered.  I just redefined it and please have another try.  Many thanks!  Feel free to let me the result

**Comment by h3xh4wk** [comment]
Thank you @zhouxj-ibm . I am able to work with Python3_Demo. 
Thanks once again.

**Comment by zhouxj-ibm** [comment]
My pleasure.
