### ISSUE TITLE
Unable to launch Analytics instance using the free trail account

### ISSUE THREAD

**Issue by saiprp** [ibmz-community-cloud/zAnalytics#4]
Unable to launch the Analytics instance (first time user).
![image](https://user-images.githubusercontent.com/7659333/72063690-4478b780-3300-11ea-891e-9ea1ce82c786.png)

https://zcloud.marist.edu/#/spark

**Comment by xingjunzhou** [comment]
Did you follow the password rules when assigning new password?  It should be no longer than 8 characters, and also some restrictions to use special characters.  Please read the README file carefully for password rules.

**Comment by saiprp** [comment]
@xingjunzhou thanks for the quick reply. I am using simple text of 8 chars length. Still getting the same message.

**Comment by xingjunzhou** [comment]
Can you let me know your z/OS IP address?  I can take a look from z/OS side

**Comment by saiprp** [comment]
I can't see the IP Address as well here other than the status. Please see below.

![image](https://user-images.githubusercontent.com/7659333/72065558-873c8e80-3304-11ea-8645-96bb04f7e6aa.png)

**Comment by xingjunzhou** [comment]
Okay, seems like the z/OS allocation process got some issues.  I will discuss with the developer and get back to you asap.  Thank you for reporting.  What is your email that used to register Community Cloud?

**Comment by saiprp** [comment]
sure, thanks much @xingjunzhou . Also, can you let me know how long it might take to get access for "Machine Learning Trial"? When I request for it, I see a message popping up "your request is under review'.

**Comment by xingjunzhou** [comment]
I think there maybe inadequate WMLz resources available for trial.   I will check.  Can you let me know your email address for registration?

**Comment by saiprp** [comment]
thanks. My registered email is : 'praneeth.sai2008@gmail.com'

**Comment by xingjunzhou** [comment]
@saiprp could you please have another try?

**Comment by saiprp** [comment]
@xingjunzhou Thanks much. I am able to see the Analytics instance now.
However, Machine learning trail seems to be at capacity.

![image](https://user-images.githubusercontent.com/7659333/72129803-8a378d80-339d-11ea-8b8d-e9e34abfe981.png)

**Comment by saiprp** [comment]
I can access the Analytics instance and spark cluster.
